# Generated by Django 4.2.16 on 2025-03-26 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.helpers.model_helper


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_researchpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatetimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='researchpapers',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='researchpapers',
            name='published_date',
        ),
        migrations.AddField(
            model_name='researchpapers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=home.helpers.model_helper.ModelHelper.user_directory_path),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=home.helpers.model_helper.ModelHelper.user_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projectfield')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.datetimemodel')),
            ],
        ),
        migrations.AddField(
            model_name='researchpapers',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.datetimemodel'),
        ),
    ]
